### ISSUE TITLE
please review

### ISSUE THREAD

**Issue by jpiaskowski** [IdahoAgStats/ctv-agriculture#31]
@adamhsparks and @janetw

A draft of the CRAN task view is avaiable for feedback (The file called "Agriculture.md"). It's following the [expected format](https://github.com/cran-task-views/ctv/blob/main/Documentation.md) for these task views. 

Most (all?) other task views use a bulleted format, so I switched to that from the paragraphs (although, there a few paragraphs to consolidate information). 

Can you please look at this, largely with copy editing in mind (e.g. misspellings, incorrect grammar, inconsistent style choices)? If you see a more substantial error, however, please bring it up.

Adam - can you please check the plant pathology section carefully? I made a few decisions about organization of that section that should be checked by an expert. 

In the meantime, I will submit what is done thus far so the CTV committee can have a look. I created a new file for additional links so we can add them in the future. My plan is the delete the file called "draft_agriculture_ctv.md" because I don't want to maintain it. However, a [close copy](https://agstats.io/post/keeping-up-with-r/) of that file is on the agstats.io website, which I plan to maintain for the foreseeable future. 

Thank you!

**Comment by adamhsparks** [comment]
Here's my thoughts on this draft so far.

I think that
- The Plant Pathology section is clearly organised and looks fine to me.
- The reference for `Ascotracer` should be "Diggle _et al._ 2002" not "Diggle 2002".
- The link to the Epidemiology task view is tenuous at best. I'm not aware of any R packages listed there that are used in plant pathology with any regularity. Some of the ideas do cross over like SIR/SEIR models but the packages are mostly specialised enough that there isn't any real use cases in plant pathology, but there's likely no harm in leaving it and may placate the CTV maintainers. :)

**Comment by jpiaskowski** [comment]
Thank you! Can you take an editing round through it?

If the epidemiology section is not relevant, then no need to include it. It sounds like it would mislead R users into thinking there are useful packages in there for ag sci. 

DSSAT was in there originally as a core package, but it's [CRAN download stats](https://hadley.shinyapps.io/cran-downloads/) are way lower than apsim, so I wondered how important it really is. Do you know any crop modellers to ask about this? 

I was leaning towards a simplifed abbreviated reference style, "Author year", regardless of the number of authors. Would you be up for updating these references if this is important to you?

**Comment by adamhsparks** [comment]
All good on the "Author year" style, I just hadn't caught that was the style. :)

I'll check, I do know that those are the two major crop/system models that are used.

I'll make a pass through the md file in the near future.

**Comment by jpiaskowski** [comment]
Perfect, thanks. I'll wait to implement the recommended changes from the CTV committee until you're done to avoid merge conflicts.

**Comment by jpiaskowski** [comment]
bumping this.

**Comment by adamhsparks** [comment]
Sorry, I've not forgotten. Just busy with work.

**Comment by adamhsparks** [comment]
I'm unsure about including GHCN. That data is akin to GSOD and NASA POWER, there is much overlap and these two are in the hydrology CTV (but GHCN isn't).

"cropgrowdays" is mentioned twice. Once on Line 16 and once on line 43, which is much more detailed and accurate, is this intended? The focus should be on evapotranspiration rather than the. weather data access I think.

I've submitted a pull request with very minor polishing leaving the more major issues for discussion here.

**Comment by jpiaskowski** [comment]
Thanks for catching the 'cropgrowdays' repeat. This was not intentional. We could make a pull request to Hydrology to add GHCN. Any more thoughts on DSSAT?

**Comment by janetw** [comment]
My apologies.
I have been down with COVID off and on for the last month and it has put me wa-a-a-y behind on many things.
I am in the lab all day today but will try to look at things tomorrow.

Janet


JANET WILLIAMS, Ph.D.
Senior Research Scientist

College of Agricultural and Life Sciences
Animal, Veterinary, and Food Sciences Dept
Office: Ag Biotech 305  Lab: Ag Biotech 316
***@***.******@***.***>
208-885-6351  |  208-874-3213 (Cell)
875 Perimeter Dr MS2330  |  Moscow ID 83844   |  United States



From: Julia Piaskowski ***@***.***>
Date: Thursday, August 4, 2022 at 8:16 AM
To: IdahoAgStats/ctv-agriculture ***@***.***>
Cc: Williams, Janet ***@***.***) ***@***.***>, Mention ***@***.***>
Subject: Re: [IdahoAgStats/ctv-agriculture] please review (Issue #31)

Thanks for catching the 'cropgrowdays' repeat. This was not intentional. We could make a pull request to Hydrology to add GHCN. Any more thoughts on DSSAT?

**Comment by jpiaskowski** [comment]
I'm finishing up polishing to submit to the CTV committee. 

* the package accessing the GHCN database also accesses several other U.S. federal databases including SSURGO (US soil survey data), so it doesn't seem to hurt to mention GHCN. 
* I left the repeated references to cropgrowdays because it the two references serve different purposes: (1) accessing a database and (2)  making agrometeorological calculations
* DSSAT added as a core package
